### PR TITLE
FEA Implement pruning using honest subsample data to fit the leaves 

### PR DESCRIPTION
**Pull request by adam2392**
Changes proposed in this pull request:
- Adds honest pruning, so no empty leaves occur within the `HonestTreeClassifier`

## Before submitting

- [ ] I've read and followed all steps in the [Making a pull request](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [ ] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [ ] If this PR fixes a bug, I've added a test that will fail without my fix.
- [ ] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

## After submitting

- [ ] All GitHub Actions jobs for my pull request have passed.

### CODE REVIEW

**Review by PSSF23 — COMMENTED** [review]
Many of the errors revolve around:
```python
ERROR treeple/tests/test_honest_forest.py - AttributeError: 'ClassifierTags' object has no attribute 'multi_output',
```

while the others are failing `test_sklearn_compatible_estimator` on "fitting with `sample_weight` is not equivalent to fitting with removed or repeated data points." 

The first is due to the recent changes in sklearn 1.6 I assume? And I'll add some tests to skip in the others.

**Review by PSSF23 — COMMENTED** [review]
@adam2392 I skipped all the failing checks, and the package doesn't see any problems so far. Is there anything else to work on except adding tests for criterion? Do you have any example in mind?

**Review by PSSF23 — APPROVED** [review]
The lack of test coverage is due to the expansion of honesty into regressors, which we currently don't have applicable cases.

**Comment by adam2392** [comment]
Merging. Thanks for the in-depth review and fixes @PSSF23 !

**Pull request merged**
