### PR TITLE
[ENH] Add option to permute per forest fraction

### PR DESCRIPTION
**Pull request by adam2392**
Discussed in Forest meeting today:

Changes proposed in this pull request:
- adds a `permute_per_forest_fraction` parameter that permutes the covariate_index a controlled number of times over the entire forest (rather than per tree)
- Helps resolve the humongous usage of RAM when using large `X`, or large forests, or many repeated jobs of `FeatureImportance*Classifier`.

## Before submitting

- [ ] I've read and followed all steps in the [Making a pull request](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [ ] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [ ] If this PR fixes a bug, I've added a test that will fail without my fix.
- [ ] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

## After submitting

- [ ] All GitHub Actions jobs for my pull request have passed.

### CODE REVIEW

**Comment by adam2392** [comment]
I'll let #143 get merged first, so I can test out changes with this new functionality

**Review by PSSF23 — COMMENTED** [review]
The tests didn't pass because some indices were not stratified during testing. I also feel the `samples` variable is used too many times, which could cause confusion. In classifier `_statistic`, `samples` could mean test indices or non-nan indices.

**Comment by PSSF23** [comment]
Should we close this?

**Comment by adam2392** [comment]
It's a simple addition that's backwards compatible so I think I can just finish adding it.

**Comment by adam2392** [comment]
Is this mergable? @PSSF23 to preserve the old behavior, just set `permute_forest_fraction = 1.0 / n_estimators`.

**Comment by PSSF23** [comment]
@adam2392 We should keep the same behavior for the `permute_per_tree` parameter, so Sam would not need to change his code. The permute fraction should default to each tree with `None` value, similar to how sklearn handles the relationship between `max_samples` and `bootstrap`. Like raising an error if fraction is not `None` when `permute_per_tree` is `False`.

**Comment by adam2392** [comment]
permute_per_tree default for Sam is `False` corresponding to no permutation per tree.

permute_per_forest_fraction = None would have the same default. Is this what you mean?

**Comment by adam2392** [comment]
> @adam2392 We should keep the same behavior for the `permute_per_tree` parameter, so Sam would not need to change his code. The permute fraction should default to each tree with `None` value, similar to how sklearn handles the relationship between `max_samples` and `bootstrap`. Like raising an error if fraction is not `None` when `permute_per_tree` is `False`.

Currently, permute_per_tree default for Sam is `False` corresponding to no permutation per tree.

With this PR, permute_per_forest_fraction = None would have the same default. Is this what you mean?

**Review by PSSF23 — APPROVED** [review]
@adam2392 Actually it might not be relevant to Sam at the current stage of implementation as he's only running statistics. 

My original thought is to preserve any current use of `permute_per_tree` and treat `permute_per_forest_fraction` as add-on to it. But as the new parameter fully covers the original use, I think it's fine to upgrade. Can you fix the error in the regressor test?

**Pull request merged**
