### PR TITLE
DOC update document references & include summary for papers at home page

### PR DESCRIPTION
**Pull request by PSSF23**
## Before submitting

- [ ] I've read and followed all steps in the [Making a pull request](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [ ] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [ ] If this PR fixes a bug, I've added a test that will fail without my fix.
- [ ] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

## After submitting

- [ ] All GitHub Actions jobs for my pull request have passed.

### CODE REVIEW

**Review by adam2392 — APPROVED** [review]
LGTM

**Review by PSSF23 — COMMENTED** [review]
TODO: add document that outlines all the relevant papers included in the package (per jovo).

@adam2392 Where you feel this document should be? Or should I update the home page to include such information?

**Comment by adam2392** [comment]
Sure you can add to homepage. 

For example: we have unsupervised forest, sporf, morf and uncertainty forest.

W/ #75 we can also have extended isolation forest.

**Review by PSSF23 — COMMENTED** [review]
Tested html locally. @adam2392 Are the build errors expected?

**Comment by adam2392** [comment]
Yes there was an error on main I didn't catch or the CIs. I fixed it in https://github.com/neurodata/scikit-tree/pull/94

But I can just merge this in first.

**Review by adam2392 — APPROVED** [review]

**Comment by adam2392** [comment]
Thanks @PSSF23 !

**Pull request merged**
