### PR TITLE
[DRAFT, ENH] Start working on oblique unsupervised splitting

### PR DESCRIPTION
**Pull request by adam2392**
Signed-off-by: Adam Li <adam2392@gmail.com>

Changes proposed in this pull request:
- implements oblique splits for unsupervised trees

Needs to update the code to use the pointer casting that is done to subclass `SplitRecord`

## Before submitting

- [ ] I've read and followed all steps in the [Making a pull request](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [ ] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [ ] If this PR fixes a bug, I've added a test that will fail without my fix.
- [ ] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

## After submitting

- [ ] All GitHub Actions jobs for my pull request have passed.

### CODE REVIEW

**Comment by jshinm** [comment]
I probably have some silly issues, but I can't seem to build using meson with the following errors. I built sklearn from split branch
```
[3/8] Generating 'sktree/tree/_un...ux-gnu.so.p/_unsup_splitter.cpp'.
FAILED: sktree/tree/_unsup_splitter.cpython-39-x86_64-linux-gnu.so.p/_unsup_splitter.cpp 
python /home/jshinm/Desktop/workstation/scikit-tree/sktree/_build_utils/cythoner.py ../sktree/tree/_unsup_splitter.pyx sktree/tree/_unsup_splitter.cpython-39-x86_64-linux-gnu.so.p/_unsup_splitter.cpp --cplus

Error compiling Cython file:
------------------------------------------------------------
...
    2. `X` array instead of `y` array is stored as the criterions are computed over the X
    array.
    """

    # XXX: requires BaseSplitter to not define "criterion"
    cdef public UnsupervisedCriterion criterion         # criterion computer
                                     ^
------------------------------------------------------------

/home/jshinm/Desktop/workstation/scikit-tree/sktree/tree/_unsup_splitter.pxd:22:38: 'criterion' redeclared 
inside cythoner: 
input file:  /home/jshinm/Desktop/workstation/scikit-tree/sktree/tree/_unsup_splitter.pyx
output file:  /home/jshinm/Desktop/workstation/scikit-tree/build/sktree/tree/_unsup_splitter.cpython-39-x86_64-linux-gnu.so.p/_unsup_splitter.cpp
Traceback (most recent call last):
  File "/home/jshinm/Desktop/workstation/scikit-tree/sktree/_build_utils/cythoner.py", line 39, in <module>
    main()
  File "/home/jshinm/Desktop/workstation/scikit-tree/sktree/_build_utils/cythoner.py", line 22, in main
    sbp.run(
  File "/home/jshinm/anaconda3/envs/sktree/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cython', '-3', '--fast-fail', '--output-file', '/home/jshinm/Desktop/workstation/scikit-tree/build/sktree/tree/_unsup_splitter.cpython-39-x86_64-linux-gnu.so.p/_unsup_splitter.cpp', '--include-dir', '/home/jshinm/Desktop/workstation/scikit-tree/build', '--cplus', '/home/jshinm/Desktop/workstation/scikit-tree/sktree/tree/_unsup_splitter.pyx']' returned non-zero exit status 1.
```

**Comment by adam2392** [comment]
Did you run poetry install?

**Comment by adam2392** [comment]
You are on the wrong branch of sklearn. I use the branch newtreev2

**Comment by jshinm** [comment]
Thank you @adam2392! As you mentioned, poetry did re-install from the new branch when I ran `poetry install` and I didn't get any error when building, but I get errors when I test using `dev.py test`.

I tried importing the package from terminal, but I get the same error that CI pipeline throws
```
ImportError: cannot import name '_unsup_criterion' from partially initialized module 'sktree.tree' (most likely due to a circular import) (/home/circleci/project/sktree/tree/__init__.py)
```

**Comment by jshinm** [comment]
@adam2392 I kind of brainstormed FastBIC implementation. It looked like the impurity now is MLE on left and right Gaussians. Is this correct? If so, where do `BIC_diff_var` and `BIC_same_var` come in (from pseudocode)?

**Comment by adam2392** [comment]
You are not following the correct API we've discussed. Also use a different branch and PR as I will use this one to develop oblique splits. 

I also don't know what/where BIC_diff and BIC_same is.

**Comment by jshinm** [comment]
> You are not following the correct API we've discussed. Also use a different branch and PR as I will use this one to develop oblique splits.
> 
> I also don't know what/where BIC_diff and BIC_same is.

I will move the conversation to my FastBIC PR. Also, I reverted my last commit!

**Pull request merged**
