### PR TITLE
ENH add StreamDecisionForest class for streaming trees

### PR DESCRIPTION
**Pull request by PSSF23**
Related to #107

Changes proposed in this pull request:

- Add `sktree.experimental.StreamDecisionForest` for streaming tree tests
- Optimize internal imports

## Before submitting

- [ ] I've read and followed all steps in the [Making a pull request](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [ ] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [ ] If this PR fixes a bug, I've added a test that will fail without my fix.
- [ ] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

## After submitting

- [ ] All GitHub Actions jobs for my pull request have passed.

### CODE REVIEW

**Review by PSSF23 — COMMENTED** [review]
WIP, will add some unit tests.

**Review by PSSF23 — COMMENTED** [review]
Seems good after the fix in fork. Can we merge this? @adam2392

**Review by adam2392 — COMMENTED** [review]
Codecov states that there are certain LOC not tested. Specifically around the swapping trees logic. Might be useful for code (and your paper) to think of a few unit-tests. A naive one that comes to mind is:

- the performance should improve as you stream iris data in w/ swaps, relative to non-swapping.

Can you also add a changelog entry?

Otw LGTM

**Comment by PSSF23** [comment]
@adam2392 I'm actually considering removing the tree swapping because it barely has any performance influences. I think I will remove it from this time of paper submission.

**Review by adam2392 — APPROVED** [review]

**Comment by adam2392** [comment]
Thanks @PSSF23 !

**Pull request merged**
