### PR TITLE
[ENH] Cython axis-aligned multi-view splitter

### PR DESCRIPTION
**Pull request by adam2392**
Closes #92 

Changes proposed in this pull request:
- Adds an experimental Cython API for multi-view splitting

I foresee multi-view as a separate submodule for now since it's a rather experimental feature that is there to support MIGHT/Co-MIGHT in Cancer research.

Multiview splitting can analogously have its axis-aligned, oblique and morf versions imo. This initial PR implements the axis-aligned multi-view approach.

**Note:** what is not done is tracking constants, which is an important feature.

## Before submitting

- [ ] I've read and followed all steps in the [Making a pull request](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [ ] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [ ] If this PR fixes a bug, I've added a test that will fail without my fix.
- [ ] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

## After submitting

- [ ] All GitHub Actions jobs for my pull request have passed.

### CODE REVIEW

**Comment by adam2392** [comment]
Possible code to sample different feature sets:

```
        # dataset1 from 0 to N
        for i in range(max_features//2):
            index = random_index_selection(dataset_1)

            rand_int(0, N, random_state)

        # dataset2 from N+1 to M 
        for i in range(max_features//2):
            index = random_index_selection(dataset_2)

            rand_int(N+1, M, random_state)
```

**Review by adam2392 — COMMENTED** [review]
Mainly files to review:

- sktree/tree/_multiview.py
- sktree/tree/_oblique_splitter.pxd
- sktree/tree/_oblique_splitter.pyx
- examples/splitters/plot_multiview_axis_aligned_splitter.py

**Comment by adam2392** [comment]
https://output.circle-artifacts.com/output/job/56f3cf6c-74a2-437c-8bc7-e86da9e52d6f/artifacts/0/dev/auto_examples/splitters/plot_multiview_axis_aligned_splitter.html#sphx-glr-auto-examples-splitters-plot-multiview-axis-aligned-splitter-py

**Review by sampan501 — APPROVED** [review]
Looks good to me! @adam2392 will there be another PR exposing a class for the multiview hypothesis test? Maybe in `forestht.py`?

**Comment by adam2392** [comment]
> Looks good to me! @adam2392 will there be another PR exposing a class for the multiview hypothesis test? Maybe in `forestht.py`?

The design allows any arbitrary tree to be used in `HonestForest`, and the hypothesis test allows any arbitrary `HonestForest` parametrization to be used, so in principle this is "possible" once this PR is merged.

However, the next PR will show a more explicit example of multi-view learning on simulated data in `examples/` to test the API out. I think there should be some guardrails in place on checking values of `feature_set_ends` relative to `X`. I need to add these still tho.

**Comment by sampan501** [comment]
I agree, I just think it would be easier for the user if the whole class was exposed the user. I imagine a class kind of like `FeatureImportanceForestClassifier` that just calls HonestForest with the correct parameters. I guess I'm referring more to the Multiview test and not specifically the splitter

**Comment by adam2392** [comment]
> I agree, I just think it would be easier for the user if the whole class was exposed the user. I imagine a class kind of like `FeatureImportanceForestClassifier` that just calls HonestForest with the correct parameters. I guess I'm referring more to the Multiview test and not specifically the splitter

Sure yeah I agree it'll be easier if we can expose a sensible interface that makes semantic sense for users. We can play around w/ the best way to do this.

**Pull request merged**
