### PR TITLE
[ENH] Optimize Unsuprf

### PR DESCRIPTION
**Pull request by adam2392**
Towards: #113 

Changes proposed in this pull request:
- Changes fastBIC to "fasterBIC" framework

## Before submitting

- [ ] I've read and followed all steps in the [Making a pull request](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [ ] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [ ] If this PR fixes a bug, I've added a test that will fail without my fix.
- [ ] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

## After submitting

- [ ] All GitHub Actions jobs for my pull request have passed.

### CODE REVIEW

**Comment by adam2392** [comment]
@PSSF23 can you add the support to honest tree and forest for partial fit to fix the CI here?

```
=========================== short test summary info ============================
FAILED sktree/tests/test_honest_forest.py::test_sklearn_compatible_estimator[HonestForestClassifier(n_estimators=10,random_state=0)-check_fit_score_takes_y] - AttributeError: 'HonestTreeClassifier' object has no attribute 'partial_fit'
FAILED sktree/tests/test_honest_forest.py::test_sklearn_compatible_estimator[HonestForestClassifier(n_estimators=10,random_state=0)-check_estimators_partial_fit_n_features] - TypeError: fit() got an unexpected keyword argument 'classes'
```

Feel free to commit directly to the branch once you have something working locally? Afterwards, I can merge this PR and the forests/trees in scikit-tree should have partial_fit enabled.

**Review by PSSF23 — COMMENTED** [review]
@adam2392 I have optimized the honest fitting as we currently have `classes` as a variable. Right now only the samples used for tree structures are included in the fitting, instead of the current `sample_weight=0` method.

**Comment by PSSF23** [comment]
`black` version 22.12.0 is affecting the linting checks. Should we update it?

**Comment by adam2392** [comment]
There are some errors in the implementation. Also do you mind adding the functionality to the forest as well?

I'm not as sure what needs to get added to partial_fit. As long as it passes the `check_estimator` unit-tests then it should be good on the CIs

**Review by PSSF23 — COMMENTED** [review]
I'm getting a strange error about `self.structure_indices_` more than the range of X. How could it be bigger than the actual sample size? @adam2392

**Review by PSSF23 — APPROVED** [review]
I think all CIs work now.

**Comment by adam2392** [comment]
Cool thanks @PSSF23!

**Pull request merged**
