### PR TITLE
change `ValueError` to `RuntimeWarning` when `n_dim < n_informative`

### LINKED ISSUE #278: ENH: Change `sktree.datasets.hyppo` simulations n_informative < n_dim from error to warning
**Is your feature request related to a problem? Please describe.**
When `n_informative > n_dim` we currently raise a ValueError. This means that every time we have a `n_dim < 256`, the user has to change both parameters.

**Describe the solution you'd like**
When `n_informative < n_dim`, we should set `n_informative = n_dim` and then raise a warning that we did so.

### PR DESCRIPTION
**Pull request by sampan501**
Closes  #278 

Changes proposed in this pull request:

- Sets `n_informative` to `n_dim` when `n_dim < n_informative`
- Raises a `RuntimeWarning`

## Before submitting

- [ ] I've read and followed all steps in the [Making a pull request](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [ ] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [ ] If this PR fixes a bug, I've added a test that will fail without my fix.
- [ ] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

## After submitting

- [ ] All GitHub Actions jobs for my pull request have passed.

### CODE REVIEW

**Comment by sampan501** [comment]
I think errors are related to some issue with `spin` and not this PR

**Review by PSSF23 — APPROVED** [review]
Agreed that the errors are not related to the changes.

**Review by PSSF23 — COMMENTED** [review]
Apparently the python version of `CircleCI` was wrong. I don't know how the tests pass in the past.

**Review by PSSF23 — COMMENTED** [review]
The issue with `build doc` was confirmed to be associated with the latest `sklearn==1.5.0`, so we should have fixed it by modifying the import path.

**Review by PSSF23 — COMMENTED** [review]
`3.11` seems too new.

**Comment by sampan501** [comment]
> `3.11` seems too new.

I only did it since I thought it might be able to fix doc build issues, but it did not

**Review by PSSF23 — APPROVED** [review]
@sampan501 doc problem solved. I'll open another one to work on tutorials so this one can be closed.

**Pull request merged**
