### PR TITLE
[ENH] Getting pvalue computation ready

### PR DESCRIPTION
**Pull request by adam2392**
Changes proposed in this pull request:
- finalizes API for estimating pvalue using Coleman, or permutation forest approach
- adds parallelization to the permutation forest sampling in the Coleman approach

Suggested # of trees is >=6_000. Suggested number of permutations in the Coleman approach is 10_000 or greater.

## Before submitting

- [ ] I've read and followed all steps in the [Making a pull request](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [ ] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [ ] If this PR fixes a bug, I've added a test that will fail without my fix.
- [ ] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

## After submitting

- [ ] All GitHub Actions jobs for my pull request have passed.

### CODE REVIEW

**Review by sampan501 — COMMENTED** [review]
This is basically just Coleman + new bootstrapping approach right?

**Comment by adam2392** [comment]
Yeah with some flexibility in the API

**Comment by sampan501** [comment]
Sweet, I'll merge when CIs are green

**Comment by sampan501** [comment]
@adam2392 I think the only thing missing is coverage. I don't believe there are any unit tests for this code

**Comment by adam2392** [comment]
> @adam2392 I think the only thing missing is coverage. I don't believe there are any unit tests for this code

Will add

**Comment by adam2392** [comment]
Lmk wdyt @sampan501 

Thru testing, I noticed that the permutation forest is different in how it computes the pvalue. It needs to check opposite directionality, since the null is slightly different I think. (so i.e. a bug), but lmk if you spot an issue

**Review by sampan501 — CHANGES_REQUESTED** [review]
Looks good except for some failed unit tests

**Review by sampan501 — APPROVED** [review]

**Pull request merged**
