### PR TITLE
FIX improve performance by updating max_features

### PR DESCRIPTION
**Pull request by PSSF23**

### CODE REVIEW

**Review by PSSF23 — COMMENTED** [review]
@adam2392 this change should improve the mv performance, which is too low in the current example.

**Comment by adam2392** [comment]
Can you paste the rendered artifact link here? I can take a look on my phone.

**Comment by PSSF23** [comment]
> Can you paste the rendered artifact link here? I can take a look on my phone.

I don't know how to access it, but the local performance is 0.64/0.57, definitely better than what we have now.

**Comment by adam2392** [comment]
For future ref: under the GH-actions: `build_docs` links to the circleCI page and `Artifacts` uploaded has the html pages

**Review by adam2392 — APPROVED** [review]

**Pull request merged**
